management/urls.py
from django.urls import path
from . import views

urlpatterns = [
    #url('add-resin/', views.add_resinInfo),
    path('add-serial/', views.add_serial),
]

order/urls.py
from django.urls import path
from django.views.generic.base import TemplateView
from . import views

urlpatterns = [
    path('', views.subscribe),
    path('cancel/<str:receipt_id>', views.cancel_payment),
    path('thank-you', TemplateView.as_view(template_name="order/thank_you.html")),
]

slicerServer/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static
from django_email_verification import urls as mail_urls
from django.contrib import admin
from . import views

admin.autodiscover()
admin.site.enable_nav_sidebar = False

urlpatterns = [
    path('admin/', admin.site.urls),
    path('manage/', include('management.urls')),
    path('accounts/', include('allauth.urls')), 
    path('', TemplateView.as_view(template_name="slicerServer/index.html")),
    path('privacy', TemplateView.as_view(template_name="slicerServer/privacypolicy.html")),
    path('terms', TemplateView.as_view(template_name="slicerServer/termsofservice.html")),
    path('product/', include('product.urls')),
    path('resin/', include('resin.urls')),
    path('setup/', include('setup.urls')),
    path('post/', include('posts.urls')),
    path('email/', include(mail_urls)),
    path('order/', include('order.urls')),
    path('taggit_autosuggest/', include('taggit_autosuggest.urls')),
    path('error/<int:errcode>', views.show_error, name = 'show_error'),
]


#static stuff
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

management/forms.py
import datetime


from django import forms
from product.models import Product, ProductSerial_batch
from datetime import date

# resin manager
class AddResinForm(forms.Form):
    def __init__(self, *args, **kwargs):
        self.product = kwargs.pop('resin')
        super(AddResinForm, self).__init__(*args, **kwargs)

    M_id = forms.CharField(max_length=50)
    bed_curing_layer = forms.IntegerField(initial=0)
    bed_curing_time = forms.IntegerField(initial=0)
    curing_time = forms.IntegerField(initial=0)
    layer_delay = forms.IntegerField(initial=0)
    z_hop_height = forms.IntegerField(initial=0)

    max_speed = forms.IntegerField(initial=0)
    init_speed = forms.IntegerField(initial=0)
    up_accel_speed = forms.IntegerField(initial=0)
    up_decel_speed = forms.IntegerField(initial=0)
    down_accel_speed = forms.IntegerField(initial=0)
    down_decel_speed = forms.IntegerField(initial=0)

    contraction_ratio = forms.FloatField(initial=0)
    led_offset = forms.FloatField(initial=0)

class AddProductSerialForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super(AddProductSerialForm, self).__init__(*args, **kwargs)

    product = forms.ModelChoiceField(label="Product ", queryset=Product.objects.all())
    expire_date = forms.DateField(label="Expire Date ", input_formats=['%Y-%m-%d'], widget=forms.DateInput(attrs={'readonly':'readonly'}), required=False)
    number = forms.IntegerField(label="Number to Create ", initial=0)
    batch = forms.ModelChoiceField(label="Serial Batch ", queryset=ProductSerial_batch.objects.all(), required=False)

management/views.py
from django.shortcuts import render
from django.conf import settings
from .forms import AddResinForm, AddProductSerialForm
from resin.models import Material
from product.models import Product, ProductSerial, ProductSerial_batch
from django.http import HttpResponseNotFound
from django.contrib.auth.decorators import login_required, permission_required
import uuid
from datetime import date

from rest_framework.decorators import api_view
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework import permissions, status


# Create your views here.

@login_required(login_url="/product/login")
@permission_required('management.edit_resin', login_url="/product/login", raise_exception=True)
def add_serial(request):
    if request.method == "POST":
        form = AddProductSerialForm(request.POST)
        if form.is_valid():
            #product_serial = ProductSerial.objects.create(**form.cleaned_data)
            serials = []
            for i in range(0, int(request.POST['number'])):
                UUID = uuid.uuid4()
                today = date.today()
                created_date = today.strftime("%Y-%m-%d")
                product = Product.objects.get(name=request.POST['product'])
                expire_date = request.POST['expire_date'] if request.POST['expire_date'] != "" else None
                batch = ProductSerial_batch.objects.get(id=request.POST['batch']) if request.POST['batch'] != "" else None
                serial = ProductSerial.objects.create(serial_number=UUID, product=product, expire_date=expire_date, created_date=created_date, batch=batch)
                serial.save()
                serials.append(UUID)

            context = {
                'form': form,
                'serials': serials
            }
            return render(request, 'management/add_serial.html', context)
    else:
        form = AddProductSerialForm()
    return render(request, 'management/add_serial.html', {'form': form})

# @login_required
# @permission_required('management.edit_resin', login_url="services.hix.co.kr/accounts/login", raise_exception=True)
# def add_resinInfo(request):
#     # check user doens't already own the product
#     if request.method == "POST":
#         try:
#             resin_info = Material.objects.get(M_id=request.POST['M_id'])
#             form = AddResinForm(request.POST, resin=resin_info)
#         except Material.DoesNotExist:
#             form = AddResinForm(request.POST, resin=request)
#         except:
#             return HttpResponseNotFound()

#         if form.is_valid():
#             register_product_serial = Material.objects.create(**form.cleaned_data)
#             register_product_serial.save()
#             return render(request, 'management/add_resin.html', {'form': form})
#     else:
#         form = AddResinForm(resin=request)
#     return render(request, 'management/add_resin.html', {'form': form})

management/templates/management/add_resin.html
{% extends 'management/base.html' %}

<title>Register Resin</title>
{% load crispy_forms_tags %}

{% block content %}
  <h1>Add Resin Info</h1>
  <hr />

  <form action=""  method="post">
    {% csrf_token %}
    <div class="form-row">
      <div class="form-group col-md-3 mb-0">
        {{ form.M_id|as_crispy_field }}
      </div>
      <div class="form-group col-md-3 mb-0">
        {{ form.bed_curing_layer|as_crispy_field }}
      </div>
    </div>
    <div class="form-row">
      <div class="form-group col-md-3 mb-0">
        {{ form.bed_curing_time|as_crispy_field }}
      </div>
      <div class="form-group col-md-3 mb-0">
        {{ form.curing_time|as_crispy_field }}
      </div>
    </div>
    <div class="form-row">
      <div class="form-group col-md-3 mb-0">
        {{ form.layer_delay|as_crispy_field }}
      </div>
      <div class="form-group col-md-3 mb-0">
        {{ form.z_hop_height|as_crispy_field }}
      </div>
    </div>
    <hr />

    <div class="form-row">
      <div class="form-group col-md-3 mb-0">
        {{ form.max_speed|as_crispy_field }}
      </div>
      <div class="form-group col-md-3 mb-0">
        {{ form.init_speed|as_crispy_field }}
      </div>
    </div>
    <div class="form-row">
      <div class="form-group col-md-3 mb-0">
        {{ form.up_accel_speed|as_crispy_field }}
      </div>
      <div class="form-group col-md-3 mb-0">
        {{ form.up_decel_speed|as_crispy_field }}
      </div>
    </div>
    <div class="form-row">
      <div class="form-group col-md-3 mb-0">
        {{ form.down_accel_speed|as_crispy_field }}
      </div>
      <div class="form-group col-md-3 mb-0">
        {{ form.down_decel_speed|as_crispy_field }}
      </div>
    </div>
    <hr />

    <div class="form-row">
      <div class="form-group col-md-3 mb-0">
        {{ form.contraction_ratio|as_crispy_field }}
      </div>
      <div class="form-group col-md-3 mb-0">
        {{ form.led_offset|as_crispy_field }}
      </div>
    </div>
    <br />
    <button type="submit" class="btn btn-success">Submit</button>
  </form>
{% endblock %}

management/templates/management/add_serial.html
{% extends 'management/base.html' %}

<title>Register Resin</title>
{% load crispy_forms_tags %}
  
{% block content %}
<h1>Add Product Serial</h1>
<hr />

<form action=""  method="post">
  {% csrf_token %}
  <div class="form-row">
    <div class="form-group col-md-2 mb-2">
      {{ form.product|as_crispy_field }}
    </div>
    <div class="form-group col-md-2 mr-5">
      {{ form.expire_date|as_crispy_field }}
    </div>
    <div class="form-group col-md-3 mb-3">
      {{ form.number|as_crispy_field }}
    </div>
    <div class="form-group col-md-3 mb-3">
      {{ form.batch|as_crispy_field }}
    </div>
    <div class="form-group col-md-3 mt-4">
      <button type="submit" class="btn btn-success">Generate</button>
    </div>
  </div>
</form>

{% if serials %}
  {% for serial in serials %}
    <h5> {{ serial }} </h5>
  {% endfor %}
{% endif %}

<script>
  $(function () {
    $("#id_expire_date").datepicker({
      format: 'yyyy-mm-dd'
    });
  });
</script>
{% endblock %}

management/templates/management/base.html
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <!-- jQuery -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>

  <!-- Fengyuan Chen's Datepicker -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/datepicker/0.6.5/datepicker.min.css" integrity="sha256-b88RdwbRJEzRx95nCuuva+hO5ExvXXnpX+78h8DjyOE=" crossorigin="anonymous" />
  <script src="https://cdnjs.cloudflare.com/ajax/libs/datepicker/0.6.5/datepicker.min.js" integrity="sha256-/7FLTdzP6CfC1VBAj/rsp3Rinuuu9leMRGd354hvk0k=" crossorigin="anonymous"></script>
</head>
<body>
  <div class="container">
    {% block content %}
    {% endblock %}
  </div>
</body>
</html>